-- Tabela EMPRESA
CREATE TABLE EMPRESA (
    ID INT PRIMARY KEY,
    Nome VARCHAR(80) NOT NULL,
    CNPJ VARCHAR(25) NOT NULL,
    Nome_responsavel VARCHAR(30),
    Email_responsavel VARCHAR(30),
    Status ENUM('ATIVO', 'INATIVO') NOT NULL
);

-- Tabela COLABORADOR
CREATE TABLE COLABORADOR (
    ID INT PRIMARY KEY,
    ID_EMPRESA INT,
    Nome VARCHAR(80) NOT NULL,
    Email VARCHAR(25),
    Departamento VARCHAR(30),
    Cargo VARCHAR(30),
    Status ENUM('ATIVO', 'INATIVO') NOT NULL,
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID)
);

-- Tabela CHAMADO
CREATE TABLE CHAMADO (
    ID INT PRIMARY KEY,
    ID_Colaborador INT,
    Descricao TEXT,
    Criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    Titulo VARCHAR(80),
    FOREIGN KEY (ID_Colaborador) REFERENCES COLABORADOR(ID)
);
